 require('lv-globals')
 require('settings')
 require('cps')
 require('plugins')
 require('lv-utils')
 require('lv-autocommands')
 vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
 require('keymappings')
 require('lv-nvimtree')
 require('colorscheme')
 require('lv-galaxyline')
 require('lv-comment')
 require('lv-compe')
 require('lv-barbar')
 require('lv-dashboard')
 require('lv-telescope')
 require('lv-gitsigns')
 require('lv-treesitter')
 require('lv-autopairs')
 require('lv-rnvimr')
 require('lv-which-key')
 require('lv-neoscroll')
 require('lv-floaterm')
 -- require('lv-sniprun')
 vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
 require('lsp')
 require('lsp.angular-ls')
 require('lsp.bash-ls')
 require('lsp.clangd')
 require('lsp.css-ls')
 require('lsp.dart-ls')
 require('lsp.docker-ls')
 -- require('lsp.efm-general-ls')
 require('lsp.elm-ls')
 require('lsp.emmet-ls')
 require('lsp.graphql-ls')
 require('lsp.go-ls')
 require('lsp.html-ls')
 require('lsp.json-ls')
 require('lsp.js-ts-ls')
 require('lsp.kotlin-ls')
 require('lsp.latex-ls')
 require('lsp.lua-ls')
 require('lsp.php-ls')
 require('lsp.python-ls')
 require('lsp.ruby-ls')
 require('lsp.rust-ls')
 require('lsp.svelte-ls')
 require('lsp.terraform-ls')
 require('lv-colorizer')
 -- require('lsp.tailwindcss-ls')
 require('lsp.vim-ls')
 require('lsp.vue-ls')
 require('lsp.yaml-ls')
